from re import A
from dotenv import load_dotenv
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage, AIMessage
from langchain_core.tools import tool
from langchain.agents import create_agent 
from dataclasses import dataclass
from langgraph.checkpoint.memory import InMemorySaver
from langchain.agents.structured_output import ToolStrategy
from langchain.tools import ToolRuntime


load_dotenv()

system_prompt = """
you are an expert weather forecaster, who speaks in poetic manner.

you have access to 2 tools:
- get_weather_for location: to get the weather for a given location
- get_user_location: to get the user's location

If the user asks for the weather, make sure you know the location. If you can tell then from
the question that they mean whereever they are, use the get_weather_for_location tool to get the weather for the location.


"""



@tool
# tool decorator is used to define a function as a tool that can be used in the LLM
def get_weather_for_location(city: str) -> str:
    """Get the current weather for a given city
    Args:
        city: The city to get the weather for (eg. New York, London, Paris)
    Returns:
        The current weather for the city (eg. sunny, rainy, cloudy)
    """

    weather_db = {
        "New York": "sunny",
        "London": "rainy",
        "Paris": "cloudy"
    }
    return weather_db.get(city, "general weather forecast: sunny")


#dataclass 
# is used to define a custom runtime context schema 
# if i want to provide additional information of the user to the agent at runtime context


@dataclass
class context:
    """ custom runtime context schema """
    user_id: str

    

@tool
def get_user_location(runtime: ToolRuntime[context]) -> str:
    """
    retrieve the user's information based on the user_id
    """

    user_id = runtime.context.user_id
    print(f"User ID: {user_id}")
    return "New York" if user_id == "123" else "London","Paris",







model=ChatOpenAI(model="gpt-5.4-mini", max_tokens=1000)


@dataclass
class response_format:
    """ response format schema for the agent """
    poetic_response: str
    weather_condition: str | None = None  #optional field



tools = [get_weather_for_location, get_user_location]

saver = InMemorySaver()

agent = create_agent(
    model=model,
    tools=tools,
    system_prompt=system_prompt,
    response_format=ToolStrategy[response_format](response_format),
    context_schema=context,
    checkpointer=saver
)

# how to send all the info to the agent and track the conversation state? that is where thread_id comes into play
# thread_id is a unique identifier for the conversation
#user_id is a unique identifier for the user
# it is used to track the conversation state and the messages in the conversation


config = {"configurable": {"thread_id": "1"}} # thread_id is a unique identifier for the conversation
# thread_id generated by the agent framework / uuid

context = context(user_id="123")
response = agent.invoke(
    {"messages": [HumanMessage(content="What is the weather for me here?")]},
    config=config,
    context=context
)
print(response)

print("--------------------------------")

print(response["structured_response"])